### ISSUE TITLE
En el menu de pausa hay dos  cuadrados blancos

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#10]
Impacto bajo.
Al pausar el juego durante una partida, en el menu hay dos cuadros blancos que no se sabe muy bien para que son

**To Reproduce**
1. Entra en un combate
2. Pausa
3. Hay dos cuadrados blancos

**Expected behavior**
No se si sirven para algo o falta alguna textura

**Comment by evapastorabanades** [comment]
A nosotros también nos pasa 
![image](https://user-images.githubusercontent.com/78255023/143508540-60c0668f-0fc8-48b6-8746-931165cf06d4.png)

**Comment by OkachuX** [comment]
Añadida indicación de que ambos cuadrados son dos espacios reservados para incluir anuncios en un futuro en el menú de pausa.
