### ISSUE TITLE
Al morir por daño hecho por un hechizo propio, no mueres y los enemigos no te atacan

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#13]
Impacto grave
En combates contra varios enemigos, si lanzas un hechizo que te debería matar, no mueres, tu vida se pone a 0 y los enemigos no te atacan más.

**To Reproduce**
1. Hacer combate contra varios enemigos
2. morir por un hechizo que te quite vida al lanzarlo
3. No mueres y los enemigos dejan de atacarte

**Expected behavior**
Mueres y los enemigos te siguen atacando

**Comment by OkachuX** [comment]
Arreglado este error. Ahora perder por daño de tus propios hechizos termina la partida correctamente.
