### ISSUE TITLE
no usabilidad en los tutoriales

### ISSUE THREAD

**Issue by Robertus06** [Fire-Meatball-Games/Spellers#15]
Impacto alto

En los tutoriales hay unas bolitas amarillas cada una de ellas es una "página" que explica algo, el problema es que no se muestra al usuario en cual estás y cuando ha pasado un rato leyendo es difícil saber cual es la siguiente bolita amarilla que tienes que pulsar

Debería resaltarse mejor la bolita en la que estás, haciendo que las demás se ven más transparentes o algo que permita reconocer fácilmente cual es la que está seleccionada
![Captura](https://user-images.githubusercontent.com/54945514/143134607-bba19f63-aa5e-4d95-bb87-3b57fb8f266d.PNG)

**Comment by OkachuX** [comment]
Añadido feedback visual al usuario indicando en que pestaña del tutorial se encuentra en cada momento.
