### ISSUE TITLE
Hechizos de gran cantidad vs baja cantidad

### ISSUE THREAD

**Issue by Robertus06** [Fire-Meatball-Games/Spellers#17]
Impacto alto

En el juego tenéis tanto hechizos de poca cantidad de daño/recuperación de vida/etc, hechizos de cantidad media de daño/etc, y hechizos de gran cantidad de daño/vida/etc. La duda es, ¿Por qué ibas a elegir un hechizo de poca cantidad cuando tienes disponibles los de gran cantidad?

Estaría bien pensar esto, o en caso de que ya tenga una lógica, explicarla claramente. Es decir, si por ejemplo es más probable que te salgan los de baja cantidad que los de gran cantidad, esto debería explicarse en algún sitio.

Aprovecho para hacer hincapié en algo que ya os han comentado anteriormente ya que tiene que ver con los hechizos, tampoco se entiende como después aparecerán en el juego... es decir, puedes ponerte una sola carta del mazo con "Imperio" por ejemplo, pero a veces aparecen para elegir "imperio" "imperio" "imperio" y los tres con el mismo nivel (III por ejemplo), lo cual no tiene mucho sentido

**Comment by OkachuX** [comment]
Añadido botón con información para cada uno de los hechizos de la mano del jugador, que puede consultar en cualquier momento. Modificados los diálogos de la historia para introducir mejor al jugador a las mecánicas de juego. Disminuida la dificultad de los hechizos de mayor nivel para que su tiempo de lanzamiento sea más acorde a la diferencia de poder con los hechizos de menor nivel. Modificada la lógica de selección de cartas para la mano del jugador en cada turno haciendo imposible que posea varias cartas iguales repetidas.
