### ISSUE TITLE
El panel de runas se cierra de manera repentina a veces.

### ISSUE THREAD

**Issue by GuilleIngVid** [Fire-Meatball-Games/Spellers#2]
Corrección: entiendo que al  clickar en una runa erronea se te cierra el hechizo, he clickado sin darme cuenta en una runa que no era y se me ha cerrado, haciendome pensar que se había bugeado.

**Comment by albertosr173** [comment]
Tambien me ha pasado

**Comment by OkachuX** [comment]
Añadido feedback para cuando clickeas una runa incorrecta en la ejecución del hechizo.
