### ISSUE TITLE
Bajar volumen

### ISSUE THREAD

**Issue by Robertus06** [Fire-Meatball-Games/Spellers#21]
Impacto bajo

El sonido no puede bajarse

Estaría bien un menú de ajustes donde poder regular la música

**Comment by evapastorabanades** [comment]
A nosotros también nos pasa.
Impacto: bajo.
Entorno: PC y móvil.
Descripción: el sonido no puede bajarse desde el juego, teniendo que realizarse en el dispositivo, y aunque teniendo el volumen al mínimo, este no deja de ser demasiado alto.
Pasos para reproducirlo: ninguno.

**Comment by OkachuX** [comment]
Se ha disminuido el volumen general del juego para compensarlo.
