### ISSUE TITLE
Desbalanceo del sistema de combate (en general).

### ISSUE THREAD

**Issue by evapastorabanades** [Fire-Meatball-Games/Spellers#22]
Impacto: medio.
Entorno: móvil y PC.
Descripción: se tarda mucho en invocar un hechizo que haga daño significativo, durante ese tiempo es muy posible que el contrincante haya invocado o ya tenga invocado un escudo que absorbe TODO el daño independientemente de la potencia del hechizo; o que en el último momento, cuando ya has lanzado el hechizo, el segundo de antes de su impacto invoque un escudo. Esto también aplica (en menor medida) a las curaciones. El jugador está tan concentrado en el crafteo de hechizos que para cuando separa la vista de las runas se ha dado cuenta que el hechizo que estaba invocando ya no es el que le conviene, dado que el enemigo en ese tiempo ha lanzado otro hechizo que el jugador no ha visto porque no estaba atento.
Pasos para reproducirlo: ninguno.

**Comment by OkachuX** [comment]
Añadido mayor feedback visual al usuario por medio de animaciones más vistosas e iconos más claros en la GUI para que el jugador vea en todo momento las acciones del rival. Añadidos una gran cantidad de hechizos para balancear los escudos, disminuyendo su nivel de poder en gran medida. Añadido un límite de escudos totales.
