### ISSUE TITLE
Desbalanceo del sistema de combate (en modo historia)

### ISSUE THREAD

**Issue by evapastorabanades** [Fire-Meatball-Games/Spellers#23]
Impacto: medio.
Entorno: PC y móvil.
Descripción: en el modo historia solo usas los hechizos más básicos, la customización del mazo no se aplica a este modo, siendo estos hechizos peores (sobre todo hablando del de daño). Este problema enfatiza el problema general del balanceo de los combates.
Pasos para reproducirlo: ninguno.

**Comment by OkachuX** [comment]
Cambiados casi en su totalidad los mazos del jugador y de sus rivales en el modo historia. Ahora los mazos de cada combate aumentan de manera progresiva en cantidad y complejidad. Cambiada la dificultad de lanzamiento de cada hechizo, haciendo que los hechizos más avanzados conlleven un mayor tiempo de lanzamiento para el jugador (mayor tamaño de panel de runas y runas de la palabra del casteo).
