### ISSUE TITLE
Runas dobles en la pantalla de runas por seleccionar

### ISSUE THREAD

**Issue by evapastorabanades** [Fire-Meatball-Games/Spellers#25]
Impacto: medio.
Entorno: PC y móvil.
Descripción: en la pantalla de runas por seleccionar no se terminan de dejar claro si estas son individuales o dobles, por lo que en caso de darte ambas opciones, tienes un 50% de acierto.
Pasos para reproducirlo: ninguno.
![image](https://user-images.githubusercontent.com/78255023/143508339-23b03446-9811-4d38-a6d2-40dce2eb49ef.png)

**Comment by OkachuX** [comment]
Cambiada la fuente a una personalizada para el juego, en que no existen runas dobles. Todas las runas son ahora únicas y singulares, haciendo que no se pueda dar esta situación.
