### ISSUE TITLE
Historia

### ISSUE THREAD

**Issue by evapastorabanades** [Fire-Meatball-Games/Spellers#26]
Impacto: bajo.
Entorno: PC y móvil.
Descripción: Al abrir el modo historia siempre aparece a la mitad de la imagen, se esperaría un comportamiento en el que se centrase en el siguiente nivel jugable, ya fuera este el 1 o el 12.
Pasos para reproducirlo: ninguno.
![image](https://user-images.githubusercontent.com/78255023/143508622-e7f05214-af15-4be8-9b3f-1e493b32c6c5.png)

**Comment by OkachuX** [comment]
Modificado el tamaño del fondo del mapa del modo de juego historia, para que el scroll vertical hasta el nivel en cuestión sea más cómodo.
