### ISSUE TITLE
Pantalla de has ganado / has perdido

### ISSUE THREAD

**Issue by evapastorabanades** [Fire-Meatball-Games/Spellers#27]
Impacto: bajo.
Entorno: PC y móvil.
Descripción: Al terminar una partida, ya sea ganada o perdida, aparecen unos símbolos poco descriptivos, que pueden dar a entender de que faltan unos stats de la partida.
Pasos para reproducirlo: ninguno.
![image](https://user-images.githubusercontent.com/78255023/143508718-4fa0ac84-9552-4ca0-9b07-406b36b98e9c.png)
![image](https://user-images.githubusercontent.com/78255023/143508948-19b580a9-8bbb-411a-a081-e8dbac8a690b.png)

**Comment by OkachuX** [comment]
Añadido sistema de puntuación final, feedback de cantidad de hechizos correctos/incorrectos y animaciones de transición para una pantalla de fin de juego más amigable con el jugador.
