### ISSUE TITLE
Tienda de hechizos

### ISSUE THREAD

**Issue by evapastorabanades** [Fire-Meatball-Games/Spellers#28]
Impacto: alto.
Entorno: PC y móvil.
Descripción: la tienda aparece completamente vacía y no se puede seleccionar ningún botón de la misma, a excepción del volver.
Pasos para reproducirlo: ninguno.
![image](https://user-images.githubusercontent.com/78255023/143509107-1bc62add-cdbd-4496-8bd1-853be71266a4.png)

**Comment by OkachuX** [comment]
La tienda no es funcional en la versión actual del juego. Incluido un cartel de "Proximamente" para que no de lugar a error.
