### ISSUE TITLE
Daño en combate

### ISSUE THREAD

**Issue by GuilleIngVid** [Fire-Meatball-Games/Spellers#3]
Impacto bajo.
Entorno: durante los combates (PC y movil).
A veces da la sensación de que los hechizos no hacen daño, puede ser que el enemigo se haya puesto un escudo en el último microsegundo o es posible que sí haya hecho daño pero al ser tan pequeño cuesta verlo en la barra de vida.
Pasos para reproducirlo: usar el ataque del meteorito en el modo historia.

**Comment by OkachuX** [comment]
Modificada la barra de vida y feedback visual de los hechizos que proporcionan efectos permanentes en el tiempo, así como los escudos.
