### ISSUE TITLE
Problema ejecución Iphone 6 

### ISSUE THREAD

**Issue by Jopabaga** [Fire-Meatball-Games/Spellers#33]
Impacto: alto.
Entorno: móvil (IOS).
Descripción: El juego se queda congelado al cabo de un rato dentro del combate en mi dispositivo.
Pasos para reproducirlo: Jugar.

**Comment by OkachuX** [comment]
Realizados cambios para funcionar en dispositivos IOS o móviles de gama baja, reduciendo el tamaño de animaciones e iconos.
