### ISSUE TITLE
Botón de minimizar

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#4]
Impacto bajo
El botón de minimizar en pantalla completa del juego, no miniminiza

**To Reproduce**
1. Pon el juego en pantalla completa
2. En la pantalla de título o el menú, dale a el boton de abajo a la derecha blanco
3. No funciona

**Expected behavior**
El juego sale de pantalla completa

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by OkachuX** [comment]
Eliminado el botón de minimizar el juego. En lugar de esto, se deberá pulsar escape para salir de la pantalla completa.
