### ISSUE TITLE
Personalización no se ve en el icono del menú

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#5]
Impacto bajo

Al cambiar la apariencia del jugador en personalización, no aparecen los cambios en la imagen del menu

**To Reproduce**
1. Personaliza al personaje
2. Sal de cualquiera de las pantallas de personalizción
3. El retarto no cambia

**Expected behavior**
El retrato de arriba a la derecha de los menús cambia según como personalices al jugador

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Comment by OkachuX** [comment]
El retrato superior izquierdo del jugador es una imagen precargada, no una miniatura de la apariencia elegida por este. Para mostrar al jugador como quedaría su personaje se ha añadido una miniatura en movimiento del mismo, que se actualiza a tiempo real a medida de que realiza cambios en la pestaña de skins.
