### ISSUE TITLE
Fallos en las skins de enemigos en cobates personalizados

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#6]
Impacto bajo.
Al hacer un combate personalizado contra varios enemigos y subirles la dificultad al máximo, su skin cambia por otra.

**To Reproduce**
1. Entrar a combate personalizado
2. Poner 2 enemigos
3. Ponerle la dificultad máxima a cualquiera
4. Al empezar la partida la skin cambia

**Expected behavior**
El enemigo tiene la skin que se ha seleccionado en la pantalla anterior

**Additional context**
El nombre del personaje se mantiene pero su skin cambia

**Comment by OkachuX** [comment]
Eliminados los combates contra múltiples enemigos en su totalidad. En combates rápidos contra un único enemigo no se da este error.
