### ISSUE TITLE
Los efectos en los personajes no se ven en la interfaz

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#7]
Impacto alto.
No se puede saber que efecto (veneno, mas daño, etc...) tiene cada personaje porque no sale en la interfaz al jugar un combate

**To Reproduce**
1. Empezar un combate
2. Hacer un hechizo de bufo/debufo
3. No se ve en la interfaz

**Expected behavior**
El efecto que tiene cada personaje se debería mostrar bajo su barra de vida, como pone en el tutorial.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Comment by albertosr173** [comment]
Creo que solo es en firefox, en operaGX si que salen los iconos de los efectos

**Comment by OkachuX** [comment]
Actualizados los iconos de la GUI a unos nuevos. Reducido el peso de los archivos para que se muestren correctamente en todos los navegadores.
