### ISSUE TITLE
Solo se ataca a un enemigo en combates contra varios

### ISSUE THREAD

**Issue by albertosr173** [Fire-Meatball-Games/Spellers#8]
Impacto alto
En combates personalizados contra varios enemigos, si se ataca al primero o al tercero, el daño lo recibe el primero

**To Reproduce**
1. Entrar a un combae personalizado contra varios enemigos
2. Atacar a uno de los enemigos que no sea el primero
3. El daño lo recibe el primero

**Expected behavior**
Al atacar a al segundo o tercer enemigo, que el daño lo reciba este

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox

**Comment by evapastorabanades** [comment]
A nosotros también nos pasa, solo recibe el daño el primer enemigo.
![image](https://user-images.githubusercontent.com/78255023/143508852-49edb34e-59c2-4316-ba71-d3e09afcdf1e.png)

**Comment by OkachuX** [comment]
Eliminados los combates contra múltiples enemigos al ser un modo de juego que requeriría muchas mejoras para resultar divertido.
